spring.application.name=backend

#postgreSql
spring.datasource.url=jdbc:postgresql://localhost:5433/insurance_claim_db
spring.datasource.username=postgres
spring.datasource.password=password


#Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format._sql=true


#PostgreSql Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Secret key used to sign tokens
jwt.secret=kV8xaYieQ8j3Ad96Utzv44p2cEqif6CcxAU/ar0t9tM=
jwt.expiration=3600000



